import * as fs from 'fs/promises';
import * as path from 'path';

import { AgenticTddService } from './typescript/services/agentic-tdd/AgenticTddService';
import { NodeFileSystemService } from './typescript/services/file-system/NodeFileSystemService';
import { IFileSystemService } from './typescript/services/file-system/IFileSystemService';
import { JestOutputParser } from './typescript/services/test-parser/JestOutputParser';
import { SimpleAiModelService } from './typescript/services/ai-model/SimpleAiModelService';
import { TestRunnerService } from './typescript/services/test-runner/TestRunnerService';
import { Specification, TestScenario } from './typescript/types/specification';
import { IAiModelService } from './typescript/services/ai-model/IAiModelService';
import { ParsedErrorDetails } from './typescript/services/test-parser/JestOutputParser';


// Make path resolution robust whether running from src (ts-node) or bin (node after tsc)
const PROJECT_ROOT = process.cwd(); // /app
const CALCULATOR_FILE_PATH = path.resolve(PROJECT_ROOT, 'src/lib/sample-project/calculator.ts');

// Store original content for restoration
let originalCalculatorContent: string;

class ConfigurableSimpleAiModelService extends SimpleAiModelService {
  async prompt(systemMessage: string, userPrompt: string, context?: any): Promise<string> {
    console.log("ConfigurableSimpleAiModelService received prompt request.");
    // console.log("System Message:", systemMessage);
    // console.log("User Prompt:", userPrompt.substring(0, 150) + "...");
    // console.log("Context:", context);

    const scenario = context as TestScenario; 
    const errorDetails = context?.parsedError as ParsedErrorDetails; 
    const analysisContext = context?.analysis as string; 

    if (userPrompt.includes("Generate a Jest test for the following scenario")) {
      if (scenario?.description === "should correctly subtract two numbers") {
        console.log(`ConfigurableAI: Generating specific test for "should correctly subtract two numbers"`);
        return `
// Test generated by ConfigurableSimpleAiModelService for Calculator.subtract
// Uses relative import, assuming calculator.ts is copied to the same temp directory.
import { Calculator } from './calculator'; 

describe('Calculator.subtract', () => {
  it('should correctly subtract two numbers', () => {
    const calculator = new Calculator();
    expect(calculator.subtract(5, 2)).toBe(3);
  });
});
        `;
      }
    } else if (userPrompt.includes("Diagnose the following Jest test failure")) {
      if (errorDetails?.testName?.includes("should correctly subtract two numbers")) {
        console.log(`ConfigurableAI: Diagnosing specific failure for "should correctly subtract two numbers"`);
        return `ConfigurableAI Diagnosis: The test 'Calculator.subtract > should correctly subtract two numbers' failed.
Error: ${errorDetails?.errorMessage || 'Method not found or incorrect implementation.'}.
Likely cause: The 'subtract' method is missing from the Calculator class or not implemented correctly.
File: ${errorDetails?.filePath || CALCULATOR_FILE_PATH}. // Using the robust CALCULATOR_FILE_PATH
Focus on implementing the 'subtract' method in '${CALCULATOR_FILE_PATH}'.`; // Using the robust CALCULATOR_FILE_PATH
      }
    } else if (userPrompt.includes("Generate a code fix for the following")) {
      if (context?.scenario?.description === "should correctly subtract two numbers") {
        console.log(`ConfigurableAI: Generating specific code fix for "should correctly subtract two numbers"`);
        const fixContent = `// src/lib/sample-project/calculator.ts
export class Calculator {
  add(a: number, b: number): number {
    return a + b;
  }

  subtract(a: number, b: number): number {
    return a - b; // The fix
  }
}`;
        return JSON.stringify({
          filePathToModify: CALCULATOR_FILE_PATH,
          codeOrDiffContent: fixContent,
          type: 'full_content'
        });
      }
    }
    
    console.warn("ConfigurableSimpleAiModelService: No specific handler for this prompt, falling back to parent or generic.");
    // Fallback to default SimpleAiModelService behavior if no override matches
    return super.prompt(systemMessage, userPrompt, context); 
  }
}


const sampleSpecification: Specification = {
  featureDescription: "Add a subtract method to the Calculator",
  affectedFiles: [CALCULATOR_FILE_PATH],
  changes: [{
    filePath: CALCULATOR_FILE_PATH,
    description: "Add a subtract(a, b) method that returns a - b.",
    type: "modification",
    targetElement: "Calculator"
  }],
  testScenarios: [{
    description: "should correctly subtract two numbers",
    type: "unit",
    focusArea: "Calculator.subtract", // Used by AI to generate test and code
    expectedOutcome: "The subtract method should be added to the Calculator class and work correctly."
  }]
};

async function main() {
  console.log("--- Starting Agentic TDD System Test Rig ---");

  let specToProcess: Specification = sampleSpecification;
  let specOrigin = "default calculator specification";

  const args = process.argv.slice(2); // Skip node executable and script path
  const specArgIndex = args.indexOf('--spec');

  if (specArgIndex !== -1 && args[specArgIndex + 1]) {
    const specFilePath = path.resolve(args[specArgIndex + 1]);
    specOrigin = `specification from: ${specFilePath}`;
    console.log(`Attempting to load ${specOrigin}`);
    try {
      const fileContent = await fs.readFile(specFilePath, 'utf-8');
      const loadedSpec = JSON.parse(fileContent) as Specification;
      
      // Basic validation - ensure it looks like a Specification object
      // This is a simplified check; a more robust validation might use a schema validator
      if (!loadedSpec.featureDescription || !loadedSpec.testScenarios || !loadedSpec.affectedFiles) {
          console.error(`Error: The file ${specFilePath} does not appear to be a valid Specification object. Missing key fields.`);
          process.exit(1);
      }
      specToProcess = loadedSpec;
      console.log(`Successfully loaded ${specOrigin}`);
    } catch (error: any) {
      if (error.code === 'ENOENT') {
        console.error(`Error: Specification file not found at ${specFilePath}`);
      } else if (error instanceof SyntaxError) {
        console.error(`Error: Could not parse specification file at ${specFilePath}. Invalid JSON. Details: ${error.message}`);
      } else {
        console.error(`Error loading or parsing specification file ${specFilePath}: ${error.message}`);
      }
      process.exit(1); // Exit if spec loading fails
    }
  } else {
    console.log(`Using ${specOrigin}.`);
  }

  const fileSystemService: IFileSystemService = new NodeFileSystemService();
  const outputParser = new JestOutputParser();
  const aiModelService: IAiModelService = new ConfigurableSimpleAiModelService(); // Remains as is
  const testRunnerService = new TestRunnerService(); // Uses Jest

  const agenticTddService = new AgenticTddService(
    testRunnerService,
    outputParser,
    aiModelService,
    fileSystemService
  );

  // The following logic for reading/restoring calculator.ts is specific to the default spec.
  // It will be skipped if a custom spec is loaded that doesn't use CALCULATOR_FILE_PATH.
  // A more generic before/after and restoration would require changes to how AgenticTddService reports changes
  // or by making the test rig aware of all targetFiles in any spec.
  let isDefaultCalculatorSpec = specToProcess === sampleSpecification;

  try {
    if (isDefaultCalculatorSpec) {
      originalCalculatorContent = await fileSystemService.readFile(CALCULATOR_FILE_PATH);
      console.log("\n--- Initial content of calculator.ts (default spec) ---");
      console.log(originalCalculatorContent);
    } else {
      // For custom specs, we won't do the specific calculator.ts before/after logging here.
      // The AgenticTddService itself logs the operations on the files specified in the custom spec.
      console.log(`\n--- Processing custom specification: ${specToProcess.featureDescription} ---`);
    }
    
    console.log(`\n--- Processing ${specOrigin} ---`);
    const success = await agenticTddService.processSpecification(specToProcess);
    console.log(`\n--- Specification processing completed for ${specOrigin}. Overall Success: ${success} ---`);

    if (isDefaultCalculatorSpec) {
      const finalCalculatorContent = await fileSystemService.readFile(CALCULATOR_FILE_PATH);
      console.log("\n--- Final content of calculator.ts (default spec) ---");
      console.log(finalCalculatorContent);

      if (success && finalCalculatorContent.includes("subtract(a: number, b: number): number")) {
          console.log("\nSUCCESS: Default calculator test rig completed, and calculator.ts was modified as expected.");
      } else if (success) {
          console.warn("\nWARNING: Default calculator test rig reported success, but calculator.ts content might not be as expected.");
      } else {
          console.error("\nFAILURE: Default calculator test rig reported failure or calculator.ts was not modified as expected.");
      }
    } else {
        // For custom specs, success is determined by AgenticTddService's output
        if (success) {
            console.log(`\nSUCCESS: Custom specification "${specToProcess.featureDescription}" processed successfully.`);
        } else {
            console.error(`\nFAILURE: Custom specification "${specToProcess.featureDescription}" processing failed.`);
        }
    }

  } catch (error) {
    console.error(`\n--- ERROR in test rig while processing ${specOrigin} ---`);
    console.error(error);
  } finally {
    // Cleanup: Restore original content only if it was the default calculator spec
    if (isDefaultCalculatorSpec && originalCalculatorContent) {
      console.log("\n--- Restoring original content of calculator.ts (default spec) ---");
      await fileSystemService.writeFile(CALCULATOR_FILE_PATH, originalCalculatorContent);
      console.log("Original content restored for default spec.");
    }
    const tempDirPattern = path.join(os.tmpdir(), 'agentic-tdd-');
    // Basic cleanup of temp dirs - more robust cleanup would be needed in a real app
    // For now, AgenticTddService cleans its own temp dir.
    console.log(`Note: Temporary test files are usually created in a sub-directory of ${os.tmpdir()} with pattern agentic-tdd-* and should be cleaned up by the service.`);
    console.log("\n--- Test Rig Finished ---");
  }
}

// Add os import for the tempDirPattern logging
import * as os from 'os';

main();
